[tool.poetry]
name = "graphify"
version = "0.1.0"
description = ""
authors = ["raul ferreira <raufer92@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
pytest = "^4.4"
networkx = "=2.1"
nxpd = "^0.2.0"
hypothesis = "^4.15"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
